let cart=[],total=0,profit=10000,isListening=false,rec=null;
const OWNER="97028392";
let shops=JSON.parse(localStorage.getItem('sahel_products')||'[{"n":"Bazin Bleu Roi","p":25000}]');
let profile=JSON.parse(localStorage.getItem('sahel_profile')||'{"name":"SAHEL LUXE","phone":"97028392"}');
// 1 MOIS GRATUIT SYSTEM
let firstUse=localStorage.getItem('sahel_first_use');
if(!firstUse){ firstUse=Date.now(); localStorage.setItem('sahel_first_use',firstUse); }
let daysLeft=Math.ceil((30*24*60*60*1000 - (Date.now()-parseInt(firstUse)))/(24*60*60*1000));
if(daysLeft<0) daysLeft=0;
let isVIP=localStorage.getItem('sahel_vip')=='true' || daysLeft>0;
let chatMsgs=JSON.parse(localStorage.getItem('sahel_chat')||'[{"t":"🎉 SAHEL LUXE V13 - 1 MOIS GRATUIT!\\n\\n📚 COURS GRATUITS PENDANT 30 JOURS!\\n🎤 Voice + 🎨 Image IA + 🎬 Video IA\\n\\nTape: Cours electomecanique\\nOu: Genere image Bazin bleu\\n\\nIl te reste '+daysLeft+' jours gratuits!","me":false}]');

function showTab(t){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.navBtn').forEach(x=>x.classList.remove('active'));document.getElementById('tab'+t).classList.add('active');let m={Chat:0,Status:1,Videos:2,Shop:3,Money:4,Post:5};document.querySelectorAll('.navBtn')[m[t]]?.classList.add('active');if(t=='Shop')renderShop();if(t=='Chat')renderChat();if(t=='Money')renderMoney();}
function speak(txt){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let c=txt.replace(/\[.*?\]/g,'').substring(0,280);let u=new SpeechSynthesisUtterance(c);let v=speechSynthesis.getVoices();u.voice=v.find(x=>x.lang.includes('fr'))||v[0];u.rate=0.95;speechSynthesis.speak(u);}
function startVoiceChat(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert("Chrome Android!");if(!rec){rec=new SR();rec.lang='fr-FR';}if(isListening){rec.stop();isListening=false;micBtn.innerText='🎤 Parler';micBtn.style.background='gold';return;}rec.onstart=()=>{isListening=true;micBtn.innerText='⏹️ J\'écoute...';micBtn.style.background='red';};rec.onresult=e=>{let t=e.results[0][0].transcript;chatMsgs.push({t:t,me:true});renderChat();setTimeout(()=>{let r=AI(t);chatMsgs.push({t:r,me:false});renderChat();speak(r);},500);};rec.onend=()=>{isListening=false;micBtn.innerText='🎤 Parler';micBtn.style.background='gold';};rec.start();}
function AI(q){let l=q.toLowerCase(),ph=OWNER;function ex(t){return t.replace(/cours|genere|cree|image|video|ia|explique/gi,'').trim()||"Bazin Riche";}
if(daysLeft<=0 &&!localStorage.getItem('sahel_vip')){
 if(!l.includes("vip")&&!l.includes("97028392")){ return `🔒 TON MOIS GRATUIT EST FINI! (30 jours)\n\n💎 Tu as aimé les cours gratuits? Deviens VIP!\n✅ Cours illimités à vie\n✅ Images/Video IA illimitées\n✅ Prix Bazin -10%\n💰 Seulement 2000F/mois!\n📲 MyNita: ${ph}\n[VIP:https://wa.me/227${ph}?text=VIP%202000F]\nTape "Je suis VIP" après paiement`; }
 if(l.includes("je suis vip")||l.includes("97028392")){localStorage.setItem('sahel_vip','true');isVIP=true;return `✅ VIP ACTIVÉ À VIE! Merci!`; }
}
if(l.includes("electro")||l.includes("ecetro")||l.includes("mecanique")){
 return `📚 COURS ELECTROMECANIQUE COMPLET - GRATUIT ${daysLeft} JOURS!\n\n🔌 CHAPITRE 1: MOTEUR ASYNCHRONE\n• Principe: U=220V, I=5A → P=U×I=1100W\n• Stator fixe crée champ tournant\n• Rotor tourne à 1500 tr/min\n\n⚡ CHAPITRE 2: DEPANNAGE\nPanne: Moteur ne démarre pas?\n1. Teste condensateur (souvent grillé)\n2. Vérifie relais thermique\n3. Roulement bloqué? Mets WD40\n\n🔧 FORMULES:\n• Couple C = P/ω\n• Glissement g = (Ns-Nr)/Ns\n\n📹 VIDEO SCHEMA:\n[IMAGE:https://image.pollinations.ai/prompt/electric%20motor%20diagram%20electromechanics%20school?width=600&height=400]\n\n💡 ASTUCE TAHOUA: Pour pompe eau, utilise moteur 2.2kW!\n\n❓ Question? Tape "Cours moteur triphasé"\n⏰ Gratuit encore ${daysLeft} jours!`;
}
if(l.includes("genere image")||l.includes("image")){
 let p=ex(q);let img=`https://image.pollinations.ai/prompt/${encodeURIComponent(p+", african bazin luxury, 8k")}?width=600&height=600&seed=${Math.floor(Math.random()*1000)}`;
 return `🎨 IMAGE IA: ${p} - GRATUIT ${daysLeft}j!\n[IMAGE:${img}]\n[WAPP:https://wa.me/227${ph}?text=${encodeURIComponent(p)}]`;
}
if(l.includes("video")){let p=ex(q);return `🎬 VIDEO IA: ${p}\n[IMAGE:https://image.pollinations.ai/prompt/${encodeURIComponent(p)}?width=512&height=912]\n[CAPCUT:https://www.capcut.com/tools/ai-video-generator?prompt=${encodeURIComponent(p)}]`;}
if(l.includes("bazin")||l.includes("je veux")||l.includes("prix")||l.includes("bonsoir")||l.includes("salam")){
 let p=ex(q);let img=`https://image.pollinations.ai/prompt/${encodeURIComponent(p||"Bazin bleu")}?width=512&height=512`;let pa=Math.floor(Math.random()*8000+12000);let tp=pa+profit;
 return `Salam! ${q} 🙏\n🛍️ ${p||"Bazin Bleu"}\n[IMAGE:${img}]\nAlibaba ${pa}F → SAHEL ${tp}F (Gagne ${profit}F!)\n⏰ Gratuit encore ${daysLeft} jours!\n[WAPP:https://wa.me/227${ph}?text=Je%20veux%20${encodeURIComponent(p)}]`;
}
return `🤖 "${q}" → Réponse gratuite! ${daysLeft} jours restants!\n📚 Tape "Cours electomecanique" ou "Genere image Bazin bleu"\n🎤 Tu peux parler avec 🎤`;
}
function renderChat(){let list=document.getElementById('chatList');if(!list)return;list.innerHTML=chatMsgs.map(m=>{let t=m.t;t=t.replace(/\[IMAGE:(.*?)\]/g,(a,u)=>`<img src="${u}" style="width:100%;border-radius:12px;margin:8px 0;border:2px solid gold">`);t=t.replace(/\[WAPP:(.*?)\]/g,(a,u)=>`<a href="${u}" target="_blank" style="display:inline-block;background:#25D366;color:#fff;padding:10px 16px;border-radius:8px;margin:6px 0;text-decoration:none;font-weight:bold">💬 WhatsApp</a>`);t=t.replace(/\[VIP:(.*?)\]/g,(a,u)=>`<a href="${u}" target="_blank" style="display:block;background:gold;color:#000;padding:12px;border-radius:12px;margin:8px 0;text-align:center;text-decoration:none;font-weight:bold">💎 VIP 2000F MyNita</a>`);t=t.replace(/\[CAPCUT:(.*?)\]/g,(a,u)=>`<a href="${u}" target="_blank" style="display:block;background:#000;color:#fff;padding:12px;border-radius:12px;margin:8px 0;text-align:center;text-decoration:none;border:2px solid #00D4FF">🎬 VIDEO IA</a>`);t=t.replace(/\[ACHAT:(.*?)\]/g,(a,u)=>`<a href="${u}" target="_blank" style="display:block;background:gold;color:#000;padding:12px;border-radius:12px;margin:8px 0;text-align:center;text-decoration:none;font-weight:bold">💰 ACHETER</a>`);t=t.replace(/\n/g,'<br>');return `<div style="background:${m.me?'gold':'#222'};color:${m.me?'#000':'#fff'};padding:12px;border-radius:16px;margin:8px;max-width:92%;${m.me?'margin-left:auto':''}">${t}${!m.me?`<button onclick="speak('${m.t.replace(/'/g,"\\'").substring(0,150)}')" style="float:right;background:gold;border:none;border-radius:50%;width:26px;height:26px">🔊</button>`:''}<div style="clear:both"></div></div>`;}).join('');list.scrollTop=list.scrollHeight;localStorage.setItem('sahel_chat',JSON.stringify(chatMsgs));}
function sendMessage(){let i=document.getElementById('chatInput');if(!i.value.trim())return;let q=i.value;chatMsgs.push({t:q,me:true});i.value='';renderChat();document.getElementById('typing').style.display='block';setTimeout(()=>{document.getElementById('typing').style.display='none';let r=AI(q);chatMsgs.push({t:r,me:false});renderChat();speak(r);},700);}
function renderShop(){let form=`<div style="background:#111;padding:12px;border-radius:12px;margin-bottom:12px;border:2px solid gold"><h4 style="color:gold">🎉 GRATUIT: ${daysLeft} jours restants!</h4><p style="color:#fff;font-size:12px">Après 30 jours → VIP 2000F/mois</p><input id="prodName" placeholder="Nom" style="width:100%;padding:10px;background:#222;color:#fff;border-radius:6px;margin:4px 0"><input id="prodPrice" type="number" placeholder="Prix Alibaba" style="width:100%;padding:10px;background:#222;color:#fff;border-radius:6px;margin:4px 0"><button onclick="addProduct()" style="width:100%;padding:12px;background:gold;color:#000;font-weight:bold;border-radius:8px;border:none">+ AJOUTER</button></div>`;let list=shops.map((s,i)=>`<div style="background:#111;border:1px solid #333;border-radius:12px;padding:10px;margin-bottom:8px;display:flex;justify-content:space-between"><div><b>${s.n}</b><br><b style="color:gold">${s.p+profit}F</b></div><button onclick="addCart(${i})" style="background:gold;color:#000;padding:8px 14px;border-radius:8px;font-weight:bold;border:none">ACHETER</button></div>`).join('');document.getElementById('shopList').innerHTML=form+list;}
function addProduct(){let n=document.getElementById('prodName').value,p=parseInt(document.getElementById('prodPrice').value);if(!n||!p)return;shops.unshift({n:n,p:p});localStorage.setItem('sahel_products',JSON.stringify(shops));renderShop();}
function addCart(i){let s=shops[i];let f=s.p+profit;cart.push({...s,p:f});total+=f;document.getElementById('cartCount').innerText=cart.length;document.getElementById('cartTotal').innerText=total.toLocaleString()+' FCFA';}
function renderMoney(){let el=document.getElementById('profileArea');if(el)el.innerHTML=`<div style="background:#111;padding:15px;border-radius:12px;text-align:center;border:1px solid gold"><b>${profile.name}</b><br>${profile.phone}<br><br>🎉 GRATUIT: ${daysLeft} jours<br>VIP: ${isVIP?'✅':'Après 30j 2000F'}<br><br><small>🎙️ Voice + 🎨 Image IA</small></div>`;}
renderChat();renderShop();renderMoney();
