let cart=[],total=0,profit=10000,isListening=false,rec=null;
const OWNER="97028392";
let shops=JSON.parse(localStorage.getItem('sahel_products')||'[{"n":"Bazin Bleu Roi","p":25000}]');
let profile=JSON.parse(localStorage.getItem('sahel_profile')||'{"name":"SAHEL LUXE","phone":"97028392"}');
let freeQ=parseInt(localStorage.getItem('sahel_free_q')||'3');
let isVIP=localStorage.getItem('sahel_vip')=='true';
let chatMsgs=JSON.parse(localStorage.getItem('sahel_chat')||'[{"t":"🎙️ V12 VOICE + 💰 GAGNE ARGENT!\\n🎤 Parle: Je veux Bazin\\n🎨 Image: Genere image Bazin bleu\\n🎬 Video: Cree video TikTok\\n📚 Cours: Cours couture\\n💰 3 questions gratuites → VIP 2000F","me":false}]');
function showTab(t){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.navBtn').forEach(x=>x.classList.remove('active'));document.getElementById('tab'+t).classList.add('active');let m={Chat:0,Status:1,Videos:2,Shop:3,Money:4,Post:5};document.querySelectorAll('.navBtn')[m[t]]?.classList.add('active');if(t=='Shop')renderShop();if(t=='Chat')renderChat();if(t=='Money')renderMoney();}
function speak(txt){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();let c=txt.replace(/\[.*?\]/g,'').substring(0,250);let u=new SpeechSynthesisUtterance(c);let v=speechSynthesis.getVoices();u.voice=v.find(x=>x.lang.includes('fr'))||v[0];u.rate=0.95;speechSynthesis.speak(u);}
function startVoiceChat(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert("Chrome Android!");if(!rec){rec=new SR();rec.lang='fr-FR';}if(isListening){rec.stop();isListening=false;micBtn.innerText='🎤 Parler';micBtn.style.background='gold';return;}rec.onstart=()=>{isListening=true;micBtn.innerText='⏹️ J\'écoute...';micBtn.style.background='red';};rec.onresult=e=>{let t=e.results[0][0].transcript;chatMsgs.push({t:t,me:true});renderChat();setTimeout(()=>{let r=AI(t);chatMsgs.push({t:r,me:false});renderChat();speak(r);},500);};rec.onend=()=>{isListening=false;micBtn.innerText='🎤 Parler';micBtn.style.background='gold';};rec.start();}
function AI(q){let l=q.toLowerCase(),ph=OWNER;function ex(t){return t.replace(/cours|genere|cree|image|video|ia|explique/gi,'').trim()||"Bazin Riche";}if(!isVIP&&freeQ<=0&&!l.includes("vip")&&!l.includes("97028392")){return `🔒 3 GRATUITES FINIES!\n💎 VIP 2000F/mois:\n✅ Illimité + Prix -10% + Images illimitées\n📲 MyNita: ${ph}\n[VIP:https://wa.me/227${ph}?text=VIP%202000F]`;}if(l.includes("je suis vip")||l.includes("97028392")){localStorage.setItem('sahel_vip','true');localStorage.setItem('sahel_free_q','1000');isVIP=true;freeQ=1000;return `✅ VIP ACTIVÉ! Questions illimitées!`; }if(l.includes("genere image")||l.includes("image")){let p=ex(q);let img=`https://image.pollinations.ai/prompt/${encodeURIComponent(p+", african bazin luxury")}?width=600&height=600&seed=${Math.floor(Math.random()*1000)}`;let o=`🎨 IMAGE IA: ${p}\n[IMAGE:${img}]\n`;if(!isVIP){freeQ--;localStorage.setItem('sahel_free_q',freeQ);o+=`Reste ${freeQ} gratuites\n`;}return o+`[WAPP:https://wa.me/227${ph}?text=${encodeURIComponent(p)}]`;}if(l.includes("video")){let p=ex(q);return `🎬 VIDEO IA: ${p}\n[IMAGE:https://image.pollinations.ai/prompt/${encodeURIComponent(p)}?width=512&height=912]\nScript: "Nouveau ${p} SAHEL LUXE ${shops[0].p+profit}F! WhatsApp ${ph}"\n[CAPCUT:https://www.capcut.com/tools/ai-video-generator?prompt=${encodeURIComponent(p)}]`;}if(l.includes("cours")||l.includes("explique")){if(l.includes("couture")){if(!isVIP)return `📚 FORMATION BAZIN (25.000F valeur)\nGratuit: Eau froide + vinaigre!\n💰 Complet 10 videos =10.000F\n[ACHAT:https://wa.me/227${ph}?text=Formation%2010000F]`;return `📚 FORMATION VIP: Mesure 5m, coupe Boubou, broderie or`; }return `📚 COURS: ${ex(q)}\nEx: Benefice = Vente - Alibaba. Si 15000→25000 = 10000F benef (66%)`; }if(l.includes("bazin")||l.includes("je veux")||l.includes("prix")){let p=ex(q);let img=`https://image.pollinations.ai/prompt/${encodeURIComponent(p)}?width=512&height=512`;let pa=Math.floor(Math.random()*8000+12000);let tp=pa+profit;let o=`🛍️ ${p}\n[IMAGE:${img}]\nAlibaba ${pa}F → SAHEL ${tp}F (Gagne ${profit}F!)\n[ALIBABA:https://www.alibaba.com/trade/search?searchText=${encodeURIComponent(p)}]\n[WAPP:https://wa.me/227${ph}?text=Je%20veux%20${encodeURIComponent(p)}%20${tp}F]`;if(!isVIP){freeQ--;localStorage.setItem('sahel_free_q',freeQ);o+=`\nReste ${freeQ} gratuites`; }return o;}let o=`🤖 "${q}" - Je réponds à voix! Dis "Genere image Bazin bleu"`;if(!isVIP){freeQ--;localStorage.setItem('sahel_free_q',freeQ);o+=`\nReste ${freeQ} gratuites`; }return o;}
function renderChat(){let list=document.getElementById('chatList');if(!list)return;list.innerHTML=chatMsgs.map(m=>{let t=m.t;t=t.replace(/\[IMAGE:(.*?)\]/g,(a,u)=>`<img src="${u}" style="width:100%;border-radius:12px;margin:8px 0;border:2px solid gold">`);t=t.replace(/\[ALIBABA:(.*?)\]/g,(a,u)=>`<a href="${u}" target="_blank" style="display:inline-block;background:#FF6A00;color:#fff;padding:8px 12px;border-radius:8px;margin:4px;text-decoration:none">🛒 Alibaba</a>`);t=t.replace(/\[WAPP:(.*?)\]/g,(a,u)=>`<a href="${u}" target="_blank" style="display:inline-block;background:#25D366;color:#fff;padding:10px 16px;border-radius:8px;margin:6px 0;text-decoration:none;font-weight:bold">💬 WhatsApp</a>`);t=t.replace(/\[VIP:(.*?)\]/g,(a,u)=>`<a href="${u}" target="_blank" style="display:block;background:gold;color:#000;padding:12px;border-radius:12px;margin:8px 0;text-align:center;text-decoration:none;font-weight:bold">💎 VIP 2000F MyNita</a>`);t=t.replace(/\[CAPCUT:(.*?)\]/g,(a,u)=>`<a href="${u}" target="_blank" style="display:block;background:#000;color:#fff;padding:12px;border-radius:12px;margin:8px 0;text-align:center;text-decoration:none;border:2px solid #00D4FF">🎬 GENERER VIDEO IA</a>`);t=t.replace(/\[ACHAT:(.*?)\]/g,(a,u)=>`<a href="${u}" target="_blank" style="display:block;background:gold;color:#000;padding:12px;border-radius:12px;margin:8px 0;text-align:center;text-decoration:none;font-weight:bold">💰 ACHETER FORMATION</a>`);t=t.replace(/\n/g,'<br>');return `<div style="background:${m.me?'gold':'#222'};color:${m.me?'#000':'#fff'};padding:12px;border-radius:16px;margin:8px;max-width:92%;${m.me?'margin-left:auto':''}">${t}${!m.me?`<button onclick="speak('${m.t.replace(/'/g,"\\'").substring(0,150)}')" style="float:right;background:gold;border:none;border-radius:50%;width:26px;height:26px">🔊</button>`:''}<div style="clear:both"></div></div>`;}).join('');list.scrollTop=list.scrollHeight;localStorage.setItem('sahel_chat',JSON.stringify(chatMsgs));}
function sendMessage(){let i=document.getElementById('chatInput');if(!i.value.trim())return;let q=i.value;chatMsgs.push({t:q,me:true});i.value='';renderChat();document.getElementById('typing').style.display='block';setTimeout(()=>{document.getElementById('typing').style.display='none';let r=AI(q);chatMsgs.push({t:r,me:false});renderChat();speak(r);},800);}
function renderShop(){let form=`<div style="background:#111;padding:12px;border-radius:12px;margin-bottom:12px;border:2px solid gold"><h4 style="color:gold">Benef ${profit}F | Gratuit: ${freeQ} | VIP:${isVIP?'✅':'❌'}</h4><input id="prodName" placeholder="Nom" style="width:100%;padding:10px;background:#222;color:#fff;border-radius:6px;margin:4px 0"><input id="prodPrice" type="number" placeholder="Prix Alibaba" style="width:100%;padding:10px;background:#222;color:#fff;border-radius:6px;margin:4px 0"><button onclick="addProduct()" style="width:100%;padding:12px;background:gold;color:#000;font-weight:bold;border-radius:8px;border:none">+ AJOUTER</button><button onclick="activateVIP()" style="width:100%;padding:8px;background:#222;color:gold;border:1px solid gold;border-radius:8px;margin-top:6px">💎 Activer VIP</button></div>`;let list=shops.map((s,i)=>`<div style="background:#111;border:1px solid #333;border-radius:12px;padding:10px;margin-bottom:8px;display:flex;justify-content:space-between"><div><b>${s.n}</b><br><b style="color:gold">${s.p+profit}F</b></div><button onclick="addCart(${i})" style="background:gold;color:#000;padding:8px 14px;border-radius:8px;font-weight:bold;border:none">ACHETER</button></div>`).join('');document.getElementById('shopList').innerHTML=form+list;}
function addProduct(){let n=document.getElementById('prodName').value,p=parseInt(document.getElementById('prodPrice').value);if(!n||!p)return;shops.unshift({n:n,p:p});localStorage.setItem('sahel_products',JSON.stringify(shops));renderShop();}
function addCart(i){let s=shops[i];let f=s.p+profit;cart.push({...s,p:f});total+=f;document.getElementById('cartCount').innerText=cart.length;document.getElementById('cartTotal').innerText=total.toLocaleString()+' FCFA';}
function renderMoney(){let el=document.getElementById('profileArea');if(el)el.innerHTML=`<div style="background:#111;padding:15px;border-radius:12px;text-align:center;border:1px solid gold"><b>${profile.name}</b><br>${profile.phone}<br><br>💰 ${profit}F/vente<br>📊 Gratuit: ${freeQ}<br>VIP:${isVIP?'✅':'❌ 2000F'}<br><br><button onclick="activateVIP()" style="background:gold;color:#000;padding:10px 16px;border-radius:8px;font-weight:bold;border:none;width:100%">💎 ACTIVER VIP</button></div>`;}
function activateVIP(){let c=prompt("Après MyNita 2000F au 97028392, tape numero ou 97028392 test:");if(c){localStorage.setItem('sahel_vip','true');localStorage.setItem('sahel_free_q','1000');isVIP=true;freeQ=1000;alert("✅ VIP ACTIVÉ!");location.reload();}}
renderChat();renderShop();renderMoney();
